/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'loyaltyPoints' : bigint,
  'phone' : string,
}
export interface MenuItem {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'tax' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Time,
  'tableId' : bigint,
  'orderType' : OrderType,
  'updatedAt' : Time,
  'discount' : bigint,
  'customerId' : [] | [bigint],
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'name' : string,
  'notes' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'ready' : null };
export type OrderType = { 'delivery' : null } |
  { 'dineIn' : null } |
  { 'takeaway' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Table {
  'id' : bigint,
  'status' : TableStatus,
  'name' : string,
  'capacity' : bigint,
}
export type TableStatus = { 'occupied' : null } |
  { 'reserved' : null } |
  { 'available' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyOrderDiscount' : ActorMethod<[bigint, bigint], Order>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCustomer' : ActorMethod<[string, string, string], Customer>,
  'createMenuItem' : ActorMethod<[bigint, string, string, bigint], MenuItem>,
  'createOrder' : ActorMethod<
    [bigint, [] | [bigint], OrderType, Array<OrderItem>],
    Order
  >,
  'createTable' : ActorMethod<[string, bigint], Table>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteTable' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTables' : ActorMethod<[], Array<Table>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[bigint], Category>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getMenuItemsByCategory' : ActorMethod<[bigint], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTable' : ActorMethod<[bigint], Table>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCategory' : ActorMethod<[bigint, string, string], Category>,
  'updateCustomer' : ActorMethod<[bigint, string, string, string], Customer>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, bigint, boolean],
    MenuItem
  >,
  'updateOrderItems' : ActorMethod<[bigint, Array<OrderItem>], Order>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], Order>,
  'updateTable' : ActorMethod<[bigint, string, bigint, TableStatus], Table>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];