/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'ready' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderType = IDL.Variant({
  'delivery' : IDL.Null,
  'dineIn' : IDL.Null,
  'takeaway' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'tableId' : IDL.Nat,
  'orderType' : OrderType,
  'updatedAt' : Time,
  'discount' : IDL.Nat,
  'customerId' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'phone' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'price' : IDL.Nat,
});
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
});
export const Table = IDL.Record({
  'id' : IDL.Nat,
  'status' : TableStatus,
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyOrderDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [Order], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
  'createMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [MenuItem],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), OrderType, IDL.Vec(OrderItem)],
      [Order],
      [],
    ),
  'createTable' : IDL.Func([IDL.Text, IDL.Nat], [Table], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deleteTable' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTable' : IDL.Func([IDL.Nat], [Table], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Category], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [MenuItem],
      [],
    ),
  'updateOrderItems' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [Order], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
  'updateTable' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, TableStatus],
      [Table],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderType = IDL.Variant({
    'delivery' : IDL.Null,
    'dineIn' : IDL.Null,
    'takeaway' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'tableId' : IDL.Nat,
    'orderType' : OrderType,
    'updatedAt' : Time,
    'discount' : IDL.Nat,
    'customerId' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
  });
  const Table = IDL.Record({
    'id' : IDL.Nat,
    'status' : TableStatus,
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyOrderDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [Order], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
    'createMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [MenuItem],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), OrderType, IDL.Vec(OrderItem)],
        [Order],
        [],
      ),
    'createTable' : IDL.Func([IDL.Text, IDL.Nat], [Table], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deleteTable' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [Category], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTable' : IDL.Func([IDL.Nat], [Table], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Category], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [MenuItem],
        [],
      ),
    'updateOrderItems' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [Order], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
    'updateTable' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, TableStatus],
        [Table],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };